backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "image", label: "Image", widget: "image" }
  - name: "about"
    label: "About"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "body", label: "Body", widget: "markdown" }
  - name: "contact"
    label: "Contact"
    files:
      - label: "Contact Page"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { name: "email", label: "Email", widget: "string" }
          - { name: "social", label: "Social Media", widget: "list" }
